name: 'Build and deploy NULIX OS with custom apps'
description: 'Build NULIX OS with custom apps, and deploy OTA updates'
author: 'NULIX'
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  step_name:
    description: 'Name of the step being executed'
    required: true
  machine:
    description: 'Machine name'
    required: false
    default: 'rpi3'
  distro:
    description: 'Distro name'
    required: false
    default: 'nulix-docker'
  compose_file:
    description: 'Docker compose YAML file name'
    required: false
    default: 'docker-compose.yml'
  base_os_ver:
    description: 'Base NULIX OS version'
    required: false
    default: '1.3.1'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.step_name }}
    - ${{ inputs.machine }}
    - ${{ inputs.distro }}
    - ${{ inputs.compose_file }}
    - ${{ inputs.base_os_ver }}
