on: [push, workflow_dispatch]

env:
  MACHINE: rpi3

jobs:
  build-os:
    runs-on: ubuntu-latest
    name: Build NULIX OS with custom apps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            action.yml
            docker-compose.yml
      - name: Build NULIX OS with custom apps
        uses: ./
        with:
          step_name: build-os
          machine: ${{ env.MACHINE }}
      - name: Upload OS image
        uses: actions/upload-artifact@v4
        with:
          name: nulix-os-${{ env.MACHINE }}-v${{ env.NULIX_OS_VER }}
          path: nulix-os/build/deploy/${{ env.MACHINE }}/nulix-os-${{ env.NULIX_OS_VER }}.img.bz2
          retention-days: 7  # Keep the artifact for 7 days
